dplyr 1 0
Crunch-io/crplyr pull request #21
Opened 2020-04-01 16:42 UTC by gergness

Fixes for the upcoming version of dplyr, and removes warnings in tests about deprecated dplyr functions.

`filter` has been updated to better match modern dplyr, but `summarize` is still a kind of unique beast, it works for basic cases, but the non-standard evaluation isn't very robust (you can't for example use `my_mean <- function(x) mean(x, na.rm)` and use `my_mean()` in a summarize call.

2020-04-01 19:42 UTC, malecki requested changes

2020-04-01 19:42 UTC, malecki commented on DESCRIPTION
> +Version: 0.3.2.9000
master is already at 0.3.3 apparently?

2020-04-01 19:42 UTC, malecki commented on DESCRIPTION
>      person("Greg", "Freedman Ellis", role="aut", email="greg@crunch.io"),
```suggestion
    person("Greg", "Freedman Ellis", role=c("aut","cre"), email="greg@crunch.io"),
```

2020-04-01 19:42 UTC, malecki commented on DESCRIPTION
>      person("Greg", "Freedman Ellis", role="aut", email="greg@crunch.io"),
(and take it off of mine)

2020-04-16 19:07 UTC, gergness reviewed
rename `as_crubble` -> `as_cr_tibble`

2020-04-23 14:43 UTC, merged